name: Add a cat gif on pr push

on:
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  contents: read

jobs:
  cats:
    name: Cat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Action Cats
        uses: ruairidhwm/action-cats@1.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
